### ISSUE TITLE
FW利用者がログ出力を使えるようにする

### ISSUE THREAD

**Issue by kiyohome** [extreal-dev/Extreal.Core.Logging#1]
## Why

- 開発のし易さにはログ出力があるとうれしい。
- ライブラリは特に中身を知らないのでログが出てないと問題に気づきにくい。
- 利用状況可視化にもつながるログ出力を用意しておきたい。

## Goals

- [x]  ログレベルを設け、ログレベルに応じたログ出力制御ができること
- [x]  ログレベル設定を事前に確認し、不要なログ文字列の作成処理を回避できること
- [x] 静的解析を導入する
- [x] ~~公開 API を定義する~~
- [x] ~~PR の CI に静的解析を追加する~~
- [x] ~~PR のテンプレートを作成する~~
- [x] README.md に開発者（コントリビュータ含む）側のメモを残す

あとはいつものゴール

- [x] ガイドに要件と使い方が書かれていること
- [x] ~~アプリチームからガイドのフィードバックをもらっていること~~
- [x] ガイドに対応するプロダクションコードと自動テストコードが作成されていること
- [x] 静的解析指摘0件、カバレッジ100%であること
- [x] ピアレビューが完了していること
- [x] 開発ブランチにマージされていること

## Tasks

- [x] 静的解析を導入する
- [x] ログレベル用の Enum を作成する
- [x] Configuration でログレベルを設定できるようにする
- [x] Configuratoin で有効なログレベルに対してログを出力できるような機構を作成する
・形式は `[LogLevel] message`
- [x] 単体テストを作成する
- [x] テストが通るよう改修する
- [x] 静的解析の指摘を 0 個にする

## Memo

FW利用者が使う実装イメージ
```
// ログ出力する人
class XxxxPresenter {

  private static readonly Logger LOGGER = LoggerManager.create(string);

  public void Start() {
    if (LOGGER.IsDebug()) {
      LOGGER.logDebug(xxxxxxxxxx);
    }
  }
}

class Logger {
  Logger(ILogWriter, ILogOutputChecker)
  bool IsDebug();
  void LogDebug(string);
  void LogDebug(string, Exception);
  bool IsInfo();
  void LogInfo(string);
  void LogInfo(string, Exception);
  GetLogleve():
  GetLoggerName();
}

interface ILogWriter {
  void LogDebug(Logger, string);
  void LogDebug(Logger, string, Exception);
  void LogInfo(Logger, string);
  void LogInfo(Logger, string, Exception);
}

interface ILogOutputChecker {
  bool IsDebug(Logger);
  bool IsInfo(Logger);
}

//設定する人
LoggerManager.SetLogWriter(ILogWriter); // 出力先を切り替えたい人
LoggerManager.SetLogOutputChecker(ILogOutputChecker); // ログ出力判定を切り替えたい人
#if DEV
Loglevel level = LogLevel.Debug;
#elif PROD
Loglevel level = LogLevel.Info;
#end
LoggerManager.SetLoglevel(level);
```

LoggerManagerクラス（staticクラス、インスタンス不可）
Loggerクラス（普通のクラス）
ILogWriter（インタフェース）
ILogOutputChecker（インタフェース）
UnityDebugLogWriter（UnityのDebugクラスで出力するクラス）
LogLevelLogOutputChecker（ログレベルでログ出力判定するクラス）

LogLevelLogOutputCheckerを1万回読んでXXミリ秒以内。
